---
# tasks file for 103-fixgrub
- name: "Checking GRUB cmdline"
  shell: "grep 'net.ifnames=0 biosdevname=0' /etc/default/grub"
  register: grub_cfg_grep
  changed_when: false
  failed_when: false

- name: "Replace grub"
  lineinfile:
    path: /etc/default/grub
    state: present
    regexp: 'GRUB_CMDLINE_LINUX="'
    line: 'GRUB_CMDLINE_LINUX="no_timer_check console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 elevator=noop"'
    # validate: '/usr/sbin/visudo -cf %s'
  when: '"net.ifnames=0 biosdevname=0" not in grub_cfg_grep'
  notify:
    - Run grub2-mkconfig


